### ISSUE TITLE
How to register expressions?

### ISSUE THREAD

**Issue by MarcoGorelli** [StefanBRas/polugins#40]
I've tried making a Python file `t.py` with
```python
from polugins import register_namespaces
import polars as pl
from polars_xdt import ExprXDTNamespace

register_namespaces(
    expression_namespaces={
        'xdt': ExprXDTNamespace,
    },
  )

pl.col('a').xdt.format_localized('%a')
```

If I type check it, I get:
```console
$ mypy t.py
t.py:1: error: Skipping analyzing "polugins": module is installed, but missing library stubs or py.typed marker  [import-untyped]
t.py:1: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
t.py:11: error: "Expr" has no attribute "xdt"; maybe "dt"?  [attr-defined]
Found 2 errors in 1 file (checked 1 source file)
```

If I run it, I get:
```console
$ python  t.py
/home/marcogorelli/tmp/.venv/lib/python3.10/site-packages/polugins/_types.py:35: UserWarning: Overriding existing custom namespace 'xdt' (on 'Expr')
  return pl.api.register_expr_namespace(name)(namespace)  # type: ignore
```

Am I doing something wrong?

**Comment by StefanBRas** [comment]
Ah yes sorry, that is an limitation that I haven't yet put in the README (https://github.com/StefanBRas/polugins/issues/29) and I maybe might just remove the ability to register them with direct imports (https://github.com/StefanBRas/polugins/issues/30).

The runtime warning is because the plugin itself registers the namespace on import. Ideally I think that packages shouldn't register extensions themselves, because then you have side effects from imports. More pragmatically everybody probably won't follow this, so I'll make check to only register if it's not already registered.

In your example it would make sense to but in the `pyproject.toml` for `xdt` that it exposes an extension (see https://github.com/StefanBRas/polugins#third-party-package-example) and then use 
```python
register_namespaces(
   load_entrypoints = True
  )
```

**Comment by StefanBRas** [comment]
I extended the README now, hopefully it makes more sense

**Comment by StefanBRas** [comment]
I removed the ability to register extensions inline like that, since it was probably more confusing than helpful. Now you have to use metadata, which is then used to generate the type stubs as well
