### ISSUE TITLE
OLD STUBS

### ISSUE THREAD

**Issue by Arengard** [StefanBRas/polugins#57]
is there a way to keep up with the weekly releases of polars ;)

```
olugins_type_gen.cli.MissingVersionException: Type stubs for version 0.20.10 does not exist. This is usually because the version has been yanked or because it's new. Feel free to create an issue if you want types for this version.
````

**Comment by StefanBRas** [comment]
Done! The stubs themselves are actually generated automatically everyday if there is a new Polars version. I just need to make a release (Which I should probably also automate).

I didn't bother making releases that often because I didn't think anyone actually used it, but nice to see that someone is!
